CREATE TABLE USERS (
    ID D_ID,
    NAME D_NAME,
    EMAIL D_EMAIL,
    CREATED_AT D_CREATED,
    CONSTRAINT PK_USERS PRIMARY KEY (ID)
);

CREATE TABLE ORDERS (
    ID D_ID,
    USER_ID D_ID,
    TOTAL_AMOUNT DECIMAL(10,2),
    CREATED_AT D_CREATED,
    CONSTRAINT PK_ORDERS PRIMARY KEY (ID)
);
